export const FETCH_CURRENT_LOCATION_BEGIN = 'FETCH_CURRENT_LOCATION_BEGIN'
export const FETCH_CURRENT_LOCATION_SUCCESS = 'FETCH_CURRENT_LOCATION_SUCCESS'
export const FETCH_CURRENT_LOCATION_FAILED = 'FETCH_CURRENT_LOCATION_FAILED'
