export const FETCH_CURRENT_WEATHER_BEGIN = 'FETCH_CURRENT_WEATHER_BEGIN'
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS'
export const FETCH_CURRENT_WEATHER_FAILED = 'FETCH_CURRENT_WEATHER_FAILED'
